# [Info]
# 左上角标题
site_name: fuzzy_han's personal website
site_url: https://iocion.github.io
site_author: fuzzy_han
site_description: 
  个人主页，包含一些项目的更新和动态
  以及一些有趣的链接和资源


# [Navigtion]
nav:
  - 笔记:
    - 随笔笔记:
      - notes/db_note.md
  - 编程语言:
    - python:
      - program_language/python/python.md
      - program_language/python/AI组第二次作业.md
      - program_language/python/AI组第三次作业.md
      - program_language/python/AI组第四次作业.md
      - program_language/python/AI组第五次作业.md
      - program_language/python/AI组第六次作业.md
      - program_language/python/环境安装.md
    - cpp:
      - program_language/cpp/cpp学习.md
    - rust:
      - program_language/rust/rust.md
  - 算法:
    - algorithm/algorithm_path.md
    - course_project:
      - algorithm/course_project/课设.md
  - 项目:
    - autooj:
      - project/autooj/autooj开发问题.md
    - project/docker部署flask项目.md
    - project/vscode远程ubuntu开发.md
  - 英语:
    - English/word_list.md
    - English/六级.md
  - Linux:
    - Linux/linux使用笔记.md
  - 课程:
    - 数据库:
      - 数据库学习:
        - course/数据库/数据库学习/sql语法.md
        - course/数据库/数据库学习/关系理论.md
      - 数据库课设:
        - course/数据库/数据库课设/mysql连接.md
        - course/数据库/数据库课设/药品进销.md
      - course/数据库/数据库开发.md
    - 操作系统:
      - course/操作系统/操作系统学习.md
    - 汇编:
      - course/汇编/汇编学习.md
    - 计组:
      - course/计组/计组学习.md
  - Git:
    - Git/Git使用笔记.md
  - 竞赛:
    - 软件杯:
      - compotition/软件杯/模拟面试平台.md
    - 数据库设计大赛:
      - compotition/数据库设计大赛/数据库设计大赛.md
      - compotition/数据库设计大赛/第一题.md
      - compotition/数据库设计大赛/第二题.md
      - compotition/数据库设计大赛/第三题.md
      - compotition/数据库设计大赛/第四题.md
    - 数学建模:
      - compotition/数学建模.md
    - 星火杯:
      - compotition/星火杯.md
  - AI:
    - AI/AI深度学习.md
    - AI/编辑器使用.md
    - AI/核心竞争力.md
    - AI/technology.md
  - 记录:
    - record/2025.4.28杭州记录.md
    - record/2025.5.5随笔.md
    - record/2025.5.9随笔.md
    - record/25.5.15数据库答辩.md
    - record/2025.6.12随笔.md
  - 其他:
    - bug:
      - Other/bug/问题分析.md
    - ssh:
      - Other/ssh/破解ssh密码.md
    - windows:
      - Other/windows/激活windows11专业.md
    - math model:
      - Other/math model/51联赛.md
    - Other/sql_injection.md
    - Other/开发.md


# # [UI]
# # [top]
theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: deep purple
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: light blue
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/iocion/iocion.github.io
repo_name: iocion.github.io
# [bottom-left corner]
# [版权说明]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: copyright iocion © 2025
# [底部的翻页]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#footer
# [bottom-right corner]
extra:
  # [添加社交网络图标和链接]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # 搜索图标：https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | iocion
      icon: fontawesome/brands/github
      link: https://github.com/iocion

# [Extensions]
plugins:
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
      # [视频支持]
      # https://squidfunk.github.io/mkdocs-material/reference/videos/
      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-videos/
      # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#video
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css

extra:
  analytics:
    provider: false  # 禁用其他分析工具，避免冲突
